### ISSUE TITLE
current version appears to be broken

### ISSUE THREAD

**Issue by jeanlucmargot** [nferraz/st#32]
Thank you for making st available.  
v1.1.4 installs and tests fine on CentOS 7.
Current version appears to be broken:

% make test
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/01-use.t .......... ok   
t/02-new.t .......... ok   
t/03-validate.t ..... ok     
t/04-process.t ...... ok   
t/05-basic-stats.t .. 1/6 
#   Failed test at t/05-basic-stats.t line 17.
#          got: '1'
#     expected: '10'

#   Failed test at t/05-basic-stats.t line 19.
#          got: '1'
#     expected: '10'

#   Failed test at t/05-basic-stats.t line 20.
#          got: '1'
#     expected: '55'

#   Failed test at t/05-basic-stats.t line 23.
#          got: '1'
#     expected: '3.02'
# Looks like you failed 4 tests of 6.
t/05-basic-stats.t .. Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/6 subtests 
t/05-format.t ....... 1/6 
#   Failed test at t/05-format.t line 20.
#          got: '1'
#     expected: '10'

#   Failed test at t/05-format.t line 22.
#          got: '1'
#     expected: '10'

#   Failed test at t/05-format.t line 23.
#          got: '1'
#     expected: '55'

#   Failed test at t/05-format.t line 27.
#          got: '1'
#     expected: '3.02765'
# Looks like you failed 4 tests of 6.
t/05-format.t ....... Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/6 subtests 
t/06-percentile.t ... 1/4 
#   Failed test at t/06-percentile.t line 26.
#          got: '1'
#     expected: '5.5'

#   Failed test at t/06-percentile.t line 26.
#          got: '1'
#     expected: '9.5'

#   Failed test at t/06-percentile.t line 26.
#          got: '1'
#     expected: '10'
# Looks like you failed 3 tests of 4.
t/06-percentile.t ... Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/4 subtests 
t/06-quantiles.t .... 1/5 
#   Failed test at t/06-quantiles.t line 27.
#          got: '1'
#     expected: '10'

#   Failed test at t/06-quantiles.t line 27.
#          got: '1'
#     expected: '3.5'

#   Failed test at t/06-quantiles.t line 27.
#          got: '1'
#     expected: '7.5'

#   Failed test at t/06-quantiles.t line 27.
#          got: '1'
#     expected: '5.5'
# Looks like you failed 4 tests of 5.
t/06-quantiles.t .... Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/5 subtests 
t/07-result.t ....... Can't call method "quartile" on unblessed reference at .../st/blib/lib/App/St.pm line 219.
t/07-result.t ....... Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 

Test Summary Report
-------------------
t/05-basic-stats.t (Wstat: 1024 Tests: 6 Failed: 4)
  Failed tests:  1, 3-4, 6
  Non-zero exit status: 4
t/05-format.t     (Wstat: 1024 Tests: 6 Failed: 4)
  Failed tests:  1, 3-4, 6
  Non-zero exit status: 4
t/06-percentile.t (Wstat: 768 Tests: 4 Failed: 3)
  Failed tests:  1-2, 4
  Non-zero exit status: 3
t/06-quantiles.t  (Wstat: 1024 Tests: 5 Failed: 4)
  Failed tests:  1-3, 5
  Non-zero exit status: 4
t/07-result.t     (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=9, Tests=55,  1 wallclock secs ( 0.04 usr  0.01 sys +  0.45 cusr  0.09 csys =  0.59 CPU)
Result: FAIL
Failed 5/9 test programs. 15/55 subtests failed.
make: *** [test_dynamic] Error 255

**Comment by nferraz** [comment]
Thanks for the report; I reverted the last merge pull request.
